services:
  - type: web
    name: quiz-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # This will be set manually in Render dashboard
      - key: WEBHOOK_URL
        sync: false  # This will be set manually in Render dashboard
